owner: daviduhden
repo: uptime

sites:
  - name: uhden.dev
    url: https://uhden.dev
  - name: Cypherpunk Handbook
    url: https://handbook.uhden.dev

status-website:
  cname: status.uhden.dev
  name: UDENIX Service Status
